language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"
before_install:
  # coveralls:
  - pip install coveralls
  # static checkers:
  - pip install flake8 py3kwarn
script:
  # Test if we .gitignore test files:
  - TMP=$(tempfile)
  - git ls-files . --exclude-standard --others | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # Test if we .gitignore any tracked files:
  - git ls-files -i --exclude-standard | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # static checkers:
  - flake8 .
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then py3kwarn .; fi
after_success:
  - coveralls
